/**
 * OpenAPI schema types for JSONPlaceholder API.
 * In a real project, this would be auto-generated by openapi-typescript
 * from an OpenAPI YAML/JSON spec:
 *   npx openapi-typescript ./api-spec.yaml -o ./src/lib/api/v1.d.ts
 */

export interface paths {
  "/users": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
            email: string;
            username: string;
          };
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
  };
  "/users/{id}": {
    get: {
      parameters: {
        path: { id: number };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: { id: number };
      };
      requestBody: {
        content: {
          "application/json": Partial<components["schemas"]["User"]>;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: { id: number };
      };
      responses: {
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/posts": {
    get: {
      parameters: {
        query?: { _limit?: number; userId?: number };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Post"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            body: string;
            userId: number;
          };
        };
      };
      responses: {
        201: {
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
      };
    };
  };
  "/posts/{id}": {
    get: {
      parameters: {
        path: { id: number };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
      };
    };
    patch: {
      parameters: {
        path: { id: number };
      };
      requestBody: {
        content: {
          "application/json": Partial<components["schemas"]["Post"]>;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Post"];
          };
        };
      };
    };
  };
  "/posts/{id}/comments": {
    get: {
      parameters: {
        path: { id: number };
      };
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Comment"][];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    User: {
      id: number;
      name: string;
      username: string;
      email: string;
      phone: string;
      website: string;
    };
    Post: {
      id: number;
      userId: number;
      title: string;
      body: string;
    };
    Comment: {
      id: number;
      postId: number;
      name: string;
      email: string;
      body: string;
    };
  };
}
